colors: true
skip_lfs: true

pre-commit:
  piped: true
  scripts:
    "check-lockfile":
      runner: bash
      priority: 1
  commands:
    format:
      run: pnpm format
      stage_fixed: true
      priority: 2
    lint:
      run: pnpm lint
      stage_fixed: true
      priority: 3
    markdownlint:
      glob: "**/*.md"
      run: pnpm exec markdownlint --ignore .changeset {staged_files}
      priority: 4
    yamllint:
      glob: "**/*.{yml,yaml}"
      run: pnpm exec yamllint {staged_files}
      priority: 5
    build:
      run: pnpm turbo build --filter="...[HEAD]"
      priority: 6

commit-msg:
  commands:
    "lint commit message":
      run: pnpm exec commitlint --edit {1}
