version: '3'

tasks:
  build:all:
    cmds:
      - task: build:style-dictionary
    desc: "Build all packages"

  build:style-dictionary:
    cmds:
      - pnpm --filter @necto/styledictionary run build:ts
      - pnpm --filter @necto/styledictionary run build:rollup
    desc: "Build Style Dictionary utilities and tools"
