name: Danger

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CI: true
  LEFTHOOK: 0

jobs:
  danger:
    name: Run Danger
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install PNPM
        uses: pnpm/action-setup@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          cache: pnpm
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts

      - name: Danger JS
        uses: danger/danger-js@9.1.6
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.NECTO_BOT_TOKEN }}
