name: Add License Header

on:
  push:
    branches: [main]

env:
  LEFTHOOK: 0

jobs:
  license_header:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Generate GitHub App token
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.NECTO_BOT_ID }}
          private_key: ${{ secrets.NECTO_BOT_KEY }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ steps.generate_token.outputs.token }}

      - name: Fix License Header
        uses: apache/skywalking-eyes/header@main
        with:
          mode: fix

      - name: Create PR with license headers
        id: create_pr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ steps.generate_token.outputs.token }}
          commit-message: 'chore: add license headers'
          title: 'chore: add license headers'
          body: 'Automated PR to add missing license headers to source files.'
          branch: chore/license-headers
          delete-branch: true

      - name: Enable auto-merge on license header PR
        if: steps.create_pr.outputs.pull-request-number
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ steps.generate_token.outputs.token }}
          pull-request-number: ${{ steps.create_pr.outputs.pull-request-number }}
          merge-method: squash
