name: Add License Header

on:
  push:
    branches: [main]

env:
  LEFTHOOK: 0

jobs:
  license_header:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fix License Header
        uses: apache/skywalking-eyes/header@main
        with:
          mode: fix

      - name: Apply Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: add license headers'
          commit_author: 'License Bot <license_bot@github.com>'
